### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bm777**
Updated the README grammar and vocabulary

### CODE REVIEW

**Comment by dgarnitz** [comment]
@bm777 just curious, did you use a script to open this PR?

**Review by dgarnitz — DISMISSED** [review]

**Comment by dgarnitz** [comment]
Thanks for taking care of this. I approved your changes but there's a merge conflict that you need to resolve before it can merge

**Comment by dgarnitz** [comment]
@bm777 he just following up to see if you plan to resolve the merge conflicts. Thanks

**Comment by bm777** [comment]
@dgarnitz solved the merge conflict in a new PR [#31](https://github.com/dgarnitz/vectorflow/pull/31)

**Comment by dgarnitz** [comment]
stale

**Pull request closed without merging**
