### PR TITLE
Debt #80 fix duplicated code

### PR DESCRIPTION
**Pull request by Aleksandir**
Hi  @dgarnitz 

Addresses issue#80.

Please let me know if you have any feedback or suggested changes 😊

### CODE REVIEW

**Comment by Aleksandir** [comment]
Hey @dgarnitz 
Apologies for all the commits, transparently I'm rather new to contributing to OS projects and have had a hard time getting VS code settings in place to not affect existing code, leading to unintended merge conflicts/changes.

I have now addressed the recent code base changes and fixed unintended auto-refactor changes I was having.

If you have any feedback, it would be greatly appreciated 😊

**Comment by dgarnitz** [comment]
@Aleksandir  This looks great! Thanks for completing this. Before it can merge tho, you need to test it using the Docker compose to ensure that the end to end flow still works. This can be done using the `setup.sh` script and the `standard_upload_client.py` in `clients`

Also please re-run all unit tests in API and worker to show they still pass. 

**Please post screen shots to prove everything works as anticipated.**

**Comment by Aleksandir** [comment]
Closing PR due to various errors and missing internal modules. have confirmed all required external modules have been installed. Unfortunately its outside of my ability to resolve these errors.

**Comment by dgarnitz** [comment]
@Aleksandir can you post the errors you were getting please? I will try to take a look at what is going wrong.

**Pull request closed without merging**
